inherit_from:
  - ../.rubocop.yml

Homebrew/MoveToExtendOS:
  Enabled: true
  Exclude:
    - "{extend,test,requirements}/**/*"
    - "os.rb"

# make rspec formatting more flexible
Layout/MultilineMethodCallIndentation:
  Exclude:
    - "**/*_spec.rb"

Naming/PredicateName:
  AllowedMethods:
    - is_32_bit?
    - is_64_bit?

Style/HashAsLastArrayItem:
  Exclude:
    - "test/utils/spdx_spec.rb"

Style/BlockDelimiters:
  BracesRequiredMethods:
    - "sig"

Bundler/GemFilename:
  Enabled: false
