inherit_from:
  - ../.rubocop.yml

Homebrew/MoveToExtendOS:
  Enabled: true
  Exclude:
    - "{extend,test,requirements}/**/*"
    - "os.rb"

# make rspec formatting more flexible
Layout/MultilineMethodCallIndentation:
  Exclude:
    - "**/*_spec.rb"

Naming/PredicateName:
  AllowedMethods:
    - is_32_bit?
    - is_64_bit?

Style/Documentation:
  AllowedConstants:
    - Homebrew
  Exclude:
    - "extend/**/*.rb"
    - "test/**/*.rb"
    - "cask/macos.rb"
    - "cli/args.rb"
    - "cli/parser.rb"
    - "cmd/list.rb"
    - "cmd/update-report.rb"
    - "dev-cmd/irb.rb"
    - "dev-cmd/pr-pull.rb"
    - "keg_relocate.rb"
    - "os/mac/keg.rb"
    - "software_spec.rb"
    - "utils.rb"
    - "utils/fork.rb"
    - "utils/git_repository.rb"
    - "utils/popen.rb"
    - "utils/shell.rb"

Style/HashAsLastArrayItem:
  Exclude:
    - "test/utils/spdx_spec.rb"

Style/BlockDelimiters:
  BracesRequiredMethods:
    - "sig"

Bundler/GemFilename:
  Enabled: false
