# Comment that will be sent if an issue is judged to be closed
comment: |
  From the issue template:

  > **Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

  If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# new feature suggestion
  - "A detailed description of the proposed feature"
  - "The motivation for the feature"
  - "How the feature would be relevant to at least 90% of Homebrew users"
  - "What alternatives to the feature have been considered"
- content:
# reproducible bug report
  - "are reporting a bug others will be able to reproduce"
  - "reproduced the problem with multiple formulae"
  - "brew update"
  - "brew doctor"
  - "brew config"
  - "What you were trying to do (and why)"
  - "What happened (include command output)"
  - "What you expected to happen"
  - "Step-by-step reproduction instructions (by running `brew` commands)"
# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: false
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
