language: ruby
rvm: 2.0.0
os: linux

matrix:
  include:
    - os: osx
      env: OSX=10.11
      osx_image: xcode7.3
      rvm: system

before_install:
  - export HOMEBREW_DEVELOPER=1
  - export PATH="bin:$PATH"
  - umask 022

script:
  - brew test-bot
