language: ruby
rvm: system
os: osx
osx_image: xcode10

cache:
  directories:
    - $HOME/Library/Caches/Homebrew/style
    - $HOME/Library/Caches/Homebrew/tests
    - Library/Homebrew/vendor/bundle

branches:
  only:
    - master

env:
  - HOMEBREW_FORCE_HOMEBREW_ON_LINUX=1

before_install:
  - HOMEBREW_REPOSITORY="$(brew --repo)"
  - sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
  # trigger vendored ruby installation
  - brew help
  - mv "$HOMEBREW_REPOSITORY/Library/Taps" "$PWD/Library"
  - sudo rm -rf "$HOMEBREW_REPOSITORY"
  - sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY"
  - travis_retry git clone --depth=1 https://github.com/Homebrew/homebrew-test-bot Library/Taps/homebrew/homebrew-test-bot

script:
  - travis_wait 60 brew test-bot

notifications:
  slack: machomebrew:1XNF7p1JRCdBUuKaeSwsWEc1
