language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode8.0
      rvm: system
    - os: linux
      rvm: 2.0.0

before_install:
  - export HOMEBREW_DEVELOPER=1
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo rm -rf "$HOMEBREW_REPOSITORY";
      ln -s "$PWD" "$HOMEBREW_REPOSITORY";
    else
      export PATH="$PWD/bin:$PATH";
      umask 022;
    fi

script:
  - brew test-bot
