language: ruby
cache:
  directories:
    - $HOME/.gem/ruby
    - $HOME/Library/Caches/Homebrew/style
    - $HOME/Library/Caches/Homebrew/tests
    - Library/Homebrew/vendor/bundle

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      rvm: system
    - os: linux
      sudo: false
      rvm: 2.0.0

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - git clone --depth=1 https://github.com/Homebrew/homebrew-test-bot Library/Taps/homebrew/homebrew-test-bot
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPOSITORY/Library/Taps";
      mv "$HOMEBREW_REPOSITORY/Library/Taps" "$PWD/Library";
      sudo rm -rf "$HOMEBREW_REPOSITORY";
      sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY";
    else
      git fetch --unshallow;
      export PATH="$PWD/bin:$PATH";
      rm -rf Library/Taps/homebrew/homebrew-test-bot/.git;
      mv Library/Taps/homebrew/homebrew-test-bot Library/Taps/homebrew/homebrew-core;
      umask 022;
    fi

script:
  - brew test-bot

notifications:
  slack: machomebrew:1XNF7p1JRCdBUuKaeSwsWEc1
