language: ruby
bundler_args: --path Library/Homebrew/vendor --standalone --jobs 3
cache: bundler

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      rvm: system
    - os: linux
      rvm: 2.0.0

before_install:
  - export GEM_HOME="$PWD/Library/Homebrew/vendor/ruby/2.0.0"
  - gem list --installed bundler || gem install bundler
  - export PATH="$GEM_HOME/bin:$PATH"
  - export HOMEBREW_DEVELOPER=1
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPOSITORY/Library/Taps";
      mv "$HOMEBREW_REPOSITORY/Library/Taps" "$PWD/Library";
      sudo rm -rf "$HOMEBREW_REPOSITORY";
      sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY";
    else
      export PATH="$PWD/bin:$PATH";
      umask 022;
    fi

script:
  - brew test-bot

notifications:
  slack: machomebrew:1XNF7p1JRCdBUuKaeSwsWEc1
