inherit_from:
  - .rubocop_common.yml

# counterproductive in formulas, notably within the install method
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false

# depends_on foo: :bar looks rubbish
Style/HashSyntax:
  Enabled: false
