inherit_from:
  - .rubocop_rules.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0
  Include:
    - '**/.simplecov'
  Exclude:
    - 'Homebrew/cask/**/*'
    - 'Homebrew/vendor/**/*'
    - 'Homebrew/test/vendor/**/*'
