name: Generate rubydoc.brew.sh
on:
  push:
    branches: master
jobs:
  apidoc:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ruby:latest
      - uses: Homebrew/actions/git-ssh@master
        with:
          git_user: BrewTestBot
          git_email: homebrew-test-bot@lists.sfconservancy.org
          key: ${{ secrets.RUBYDOC_DEPLOY_KEY }}
      - run: |
          # silence bundler complaining about being root
          mkdir ~/.bundle
          echo 'BUNDLE_SILENCE_ROOT_WARNING: "1"' > ~/.bundle/config
          
          # clone rubydoc.brew.sh with SSH so we can push back
          git clone git@github.com:Homebrew/rubydoc.brew.sh
          cd rubydoc.brew.sh

          # clone latest Homebrew/brew
          git clone --depth=1 https://github.com/Homebrew/brew

          # run rake to build documentation
          gem install bundler
          bundle install
          bundle exec rake

          # commit and push generated files
          git add docs
          
          if ! git diff --exit-code HEAD -- docs; then
            git commit -m 'docs: update from Homebrew/brew push' docs
            git push
          fi
