name: brew doctor
on:
  pull_request:
    paths:
      - .github/workflows/doctor.yml
      - Library/Homebrew/cmd/doctor.rb
      - Library/Homebrew/diagnostic.rb
      - Library/Homebrew/extend/os/diagnostic.rb
      - Library/Homebrew/extend/os/mac/diagnostic.rb
      - Library/Homebrew/os/mac/xcode.rb
permissions:
  contents: read
env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
jobs:
  tests:
    strategy:
      matrix:
        runner:
          - "13-arm64-${{github.run_id}}-${{github.run_attempt}}"
          - "12-arm64"
          - "12-${{github.run_id}}-${{github.run_attempt}}"
          - "11-arm64"
          - "11-${{github.run_id}}-${{github.run_attempt}}"
          - "10.15-${{github.run_id}}-${{github.run_attempt}}"
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    env:
      PATH: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    defaults:
      run:
        working-directory: /tmp
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew test-bot --only-cleanup-before
        if: !contains(matrix.runner, github.run_id)

      - run: brew doctor

      - run: brew test-bot --only-cleanup-after
        if: always() && !contains(matrix.runner, github.run_id)
