name: Update SPDX license data
on:
  push:
    paths:
      - .github/workflows/spdx.yml
  schedule:
    - cron: '0 */12 * * *'
jobs:
  spdx:
    if: github.repository == 'Homebrew/brew'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: BrewTestBot

      - name: Update SPDX license data
        id: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd "$GITHUB_WORKSPACE/Library/Homebrew"

          if brew update-license-data --fail-if-not-changed; then
            if ! git ls-remote --exit-code --heads origin spdx-update; then
              git checkout -B spdx-update
              git reset origin/master
              git add data/spdx
              git commit -m "spdx: update license data." -m "Autogenerated by [a scheduled GitHub Action](https://github.com/Homebrew/brew/blob/master/.github/workflows/spdx.yml)."
              echo "::set-output name=committed::true"
            fi
          fi

      - name: Push commits
        if: steps.update.outputs.committed == 'true'
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          branch: spdx-update

      - name: Open a pull request
        if: steps.update.outputs.committed == 'true'
        run: |
          cd "$GITHUB_WORKSPACE/Library/Homebrew"
          hub pull-request --no-edit
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
